---
defconfig_name: "arm64_bootloaders_ls1046_defconfig"
append_files:
    - config_file: "external/configs/arm64_bootloaders_ls1046_defconfig"
      files:
        - br_target/br_target_arm64.config
        - br_toolchain/br_toolchain_arm64_glib.config
        - br_misc/br_tuning.config
        - br_uboot/br_uboot_ls1046.config
        - br_uboot/br_uboot_utils.config
      inline: |
        # BR2_TARGET_ROOTFS_TAR is not set

output_packet: "mscc-brsdk-arm64"
output_path: "arm64-armv8_a-linux-gnu/bootloaders/ls1046"
arch: "arm64"
