---
defconfig_name: "arm64_bootloaders_defconfig"
append_files:
    - config_file: "external/configs/arm64_bootloaders_defconfig"
      files:
        - br_target/br_target_arm64.config
        - br_toolchain/br_toolchain_arm64_glib.config
        - br_misc/br_tuning.config
        - br_uboot/br_muboot_arm64.config
        - br_uboot/br_uboot_utils.config
      inline: |
        # BR2_TARGET_ROOTFS_TAR is not set
        BR2_PACKAGE_HOST_MSCC_ATF=y
        BR2_PACKAGE_HOST_MSCC_ATF_VERSION="v2.8.8-mchp1"
        BR2_ROOTFS_POST_IMAGE_SCRIPT="board/lan969x/gen-uboot.rb"

output_packet: "mscc-brsdk-arm64"
output_path: "arm64-armv8_a-linux-gnu/bootloaders/release"
arch: "arm64"
