---
defconfig_name: "mipsel_bootloaders_defconfig"
append_files:
    - config_file: "external/configs/mipsel_bootloaders_defconfig"
      files:
        - br_target/br_target_mips.config
        - br_toolchain/br_toolchain_mips_glib.config
        - br_misc/br_tuning.config
        - br_uboot/br_muboot_mipsel.config
        - br_uboot/br_uboot_utils.config
      inline: |
        # BR2_TARGET_ROOTFS_TAR is not set
        BR2_ROOTFS_POST_IMAGE_SCRIPT="board/mscc/rename-sign-uboot.rb"

output_packet: "mscc-brsdk-mipsel"
output_path: "mipsel-mips32r2-linux-gnu/bootloaders/release"
arch: "mips"
